from kivy.uix.boxlayout import BoxLayout
from kivy.uix.label import Label


class OwnedCards(BoxLayout):

    def __init__(self, **kwargs):
        super(OwnedCards, self).__init__(**kwargs)
        red_cards = BoxLayout(orientation='vertical')
        red_label = Label(text='red')
        red_num = Label(text='num=0')
        red_points = Label(text='points=0')
        red_cards.add_widget(red_label)
        red_cards.add_widget(red_num)
        red_cards.add_widget(red_points)
        self.add_widget(red_cards)
        green_cards = BoxLayout(orientation='vertical')
        green_label = Label(text='green')
        green_num = Label(text='num=0')
        green_points = Label(text='points=0')
        green_cards.add_widget(green_label)
        green_cards.add_widget(green_num)
        green_cards.add_widget(green_points)
        self.add_widget(green_cards)
        blue_cards = BoxLayout(orientation='vertical')
        blue_label = Label(text='blue')
        blue_num = Label(text='num=0')
        blue_points = Label(text='points=0')
        blue_cards.add_widget(blue_label)
        blue_cards.add_widget(blue_num)
        blue_cards.add_widget(blue_points)
        self.add_widget(blue_cards)
        black_cards = BoxLayout(orientation='vertical')
        black_label = Label(text='black')
        black_num = Label(text='num=0')
        black_points = Label(text='points=0')
        black_cards.add_widget(black_label)
        black_cards.add_widget(black_num)
        black_cards.add_widget(black_points)
        self.add_widget(black_cards)
        white_cards = BoxLayout(orientation='vertical')
        white_label = Label(text='white')
        white_num = Label(text='num=0')
        white_points = Label(text='points=0')
        white_cards.add_widget(white_label)
        white_cards.add_widget(white_num)
        white_cards.add_widget(white_points)
        self.add_widget(white_cards)
        neutral_cards = BoxLayout(orientation='vertical')
        neutral_label = Label(text='neutral')
        neutral_points = Label(text='points=0')
        neutral_cards.add_widget(neutral_label)
        neutral_cards.add_widget(Label())
        neutral_cards.add_widget(neutral_points)
        self.add_widget(neutral_cards)
        points_crowns = BoxLayout(orientation='vertical')
        total_points = Label(text='total points=0')
        total_crowns = Label(text='crowns=0')
        points_crowns.add_widget(total_points)
        points_crowns.add_widget(total_crowns)
        self.add_widget(points_crowns)
